# Autograd

  In Pytorch,central of neural networks is the **autograd** package.
  
  The autograd package provides **automatic differentiation** for all operations on Tensors. It is a **define-by-run framework**, which means that your **backprop** is **defined by how your code is run**, and that every single iteration can be different.
  
  torch.Tensor:
  1. torch.Tensor.requires_grad (True/False)
  2. torch.Tensor.backward() 
  3. torch.Tensor.grad
  4. torch.Tensor.grad_fn (refer to a function that has created the `Tensor`) 
  
  with torch.no_grad():
     

In [1]:
import torch

In [2]:
x = torch.ones(2, 2)
print(torch.mul(x,x))

tensor([[1., 1.],
        [1., 1.]])


In [3]:
x2 = torch.ones(2, 2,requires_grad=True)
print(torch.mul(x,x))

tensor([[1., 1.],
        [1., 1.]])


In [4]:
y = 1+x2
print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [5]:
#y was created as a result of an operation, so it has a grad_fn.
print(y.grad_fn)

In [6]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[12., 12.],
        [12., 12.]], grad_fn=<MulBackward0>) tensor(12., grad_fn=<MeanBackward0>)


In [27]:
out.backward(retain_graph=True)

In [28]:
print(x2.grad)

tensor([[30., 30.],
        [30., 30.]])


In [9]:
print(y.grad)

None


In [10]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)  #default fault

a.requires_grad_(True)
print(a.requires_grad)

b = (a * a).sum()
print(b.grad_fn)

False
True
