# Torch Tensors
  Tensors are simialr to Numpy's ndarrays, but it can be used on GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)   #appear num in allocated memory
print(x)

tensor([[-2.3459e-02,  4.5611e-41, -2.3459e-02],
        [ 4.5611e-41,         nan,  1.6255e-43],
        [ 7.6194e+31,  1.5564e+28,  4.7984e+30],
        [ 6.2121e+22,  1.8370e+25,  1.4603e-19],
        [ 2.7517e+12,  7.5338e+28,  3.0313e+32]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5914, 0.2507, 0.7127],
        [0.5303, 0.9968, 0.1475],
        [0.6221, 0.7641, 0.3974],
        [0.7177, 0.6848, 0.6258],
        [0.9346, 0.6602, 0.0625]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-2.1141,  1.0217,  1.0671],
        [ 1.0098,  0.2472,  0.2005],
        [ 1.1072, -1.9109, -0.8201],
        [-0.6023, -1.3459, -0.5210],
        [ 0.4086, -0.0101, -0.8380]])


In [7]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-1.4159,  1.6763,  1.9912],
        [ 1.0876,  0.4051,  0.7216],
        [ 1.2766, -1.5545, -0.3830],
        [-0.3260, -0.3670,  0.1319],
        [ 1.2037,  0.1743, -0.7396]])


In [9]:
print(torch.add(x, y))

tensor([[-1.4159,  1.6763,  1.9912],
        [ 1.0876,  0.4051,  0.7216],
        [ 1.2766, -1.5545, -0.3830],
        [-0.3260, -0.3670,  0.1319],
        [ 1.2037,  0.1743, -0.7396]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)


tensor([[-1.4159,  1.6763,  1.9912],
        [ 1.0876,  0.4051,  0.7216],
        [ 1.2766, -1.5545, -0.3830],
        [-0.3260, -0.3670,  0.1319],
        [ 1.2037,  0.1743, -0.7396]])


In [11]:
# +=
y.add_(x)
print(y)

tensor([[-1.4159,  1.6763,  1.9912],
        [ 1.0876,  0.4051,  0.7216],
        [ 1.2766, -1.5545, -0.3830],
        [-0.3260, -0.3670,  0.1319],
        [ 1.2037,  0.1743, -0.7396]])


In [12]:
# NumPy-like indexing
print(x)
print(x[:, 1])

tensor([[-2.1141,  1.0217,  1.0671],
        [ 1.0098,  0.2472,  0.2005],
        [ 1.1072, -1.9109, -0.8201],
        [-0.6023, -1.3459, -0.5210],
        [ 0.4086, -0.0101, -0.8380]])
tensor([ 1.0217,  0.2472, -1.9109, -1.3459, -0.0101])


In [28]:
#resize
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1,8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())
x[2][2]=3
print(x[2][2])

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor(3.)


In [14]:
x = torch.randn(1)
print(x)
print(x.item())
print(type(x.item()))

tensor([0.0098])
0.009844702668488026
<class 'float'>


# Bridge between Numpy
  share their memort location if one is generated by another

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# CUDA Tensors

In [29]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
    
    
    # no gpu